# Generated by Django 5.1.3 on 2024-11-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True},
        ),
    ]
