# Generated by Django 5.1.3 on 2024-11-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True},
        ),
    ]
