# Generated by Django 5.1.3 on 2024-11-28 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_match_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'managed': False},
        ),
    ]
